In [5]:
import numpy as np 

In [27]:
oneD_arr = np.array([1,2,3,4,5,6])
multiD_arr = np.reshape(oneD_arr, (2,3))
print(multiD_arr)

[[1 2 3]
 [4 5 6]]


In [16]:
b = np.arange(3,9,)
print(b)

[3 4 5 6 7 8]


In [21]:
lin_spaced_arr = np.linspace(0,100,5,dtype = int)
print(lin_spaced_arr)

[  0  25  50  75 100]


In [23]:
twoD_arr = np.array([[1,2,3], [4,5,6]])
print(twoD_arr)

[[1 2 3]
 [4 5 6]]


In [28]:
multiD_arr.ndim

2

In [29]:
multiD_arr.shape

(2, 3)

In [31]:
multiD_arr.size

6

In [34]:
arr_1 = np.array([2,4,6])
arr_2 = np.array([1,3,5])

addition = arr_1 + arr_2
print(addition)

sub = arr_1 - arr_2
print(sub)

prod = arr_1 * arr_2
print(prod)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


In [35]:
vector = np.array([1,2])
vector * 1.6

array([1.6, 3.2])

In [43]:
sliced_arr = twoD_arr[:,1]
print(sliced_arr)

[2 5]


In [45]:
a1 = np.array([[1,1],
               [2,2]])
a2 = np.array([[3,3],
               [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [46]:
vert_stack = np.vstack((a1,a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [48]:
horz_stack = np.hstack((a1,a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]


In [54]:
A = np.array([
    [-1,3],
    [3,2]
    ],dtype = np.dtype(float))

b = np.array([7,1], dtype = np.dtype(float))

print("Matrix A:")
print(A)
print("\n Array b:")
print(b)

Matrix A:
[[-1.  3.]
 [ 3.  2.]]

 Array b:
[7. 1.]


In [56]:
print(f"Shape of A: {A.shape}")
print(f"Shape of b: {b.shape}")

Shape of A: (2, 2)
Shape of b: (2,)


In [57]:
 x = np.linalg.solve(A,b)
print(f"SOlution : {x}")

SOlution : [-1.  2.]


In [58]:
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d: 2f}")

Determinant of matrix A: -11.000000


In [59]:

A_2 = np.array([
        [-1, 3],
        [3, -9]
    ], dtype=np.dtype(float))

b_2 = np.array([7, 1], dtype=np.dtype(float))

d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00


In [64]:
try:
    x_2 = np.linalg.solve(A_2, b_2)
except np.linalg.LinAlgError as err:
    print(err)

Singular matrix


In [6]:
A = np.array([
        [2,-1,1,1],
        [1,2,-1,-1],
        [-1,2,2,2],
        [1,-1,2,1]
    ], dtype = np.dtype(float))
b = np.array([6,3,14,8], dtype = np.dtype(float))


In [7]:
x = np.linalg.solve(A,b)
print(f"Solution vector {x}")

Solution vector [2. 3. 4. 1.]


In [9]:
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d:2f}")

Determinant of matrix A: -17.000000
