In [1]:
import numpy as np 

In [8]:
A = np.array([
        [2,-1,1,1],
        [1,2,-1,-1],
        [-1,2,2,2],
        [1,-1,2,1]
    ],dtype = np.dtype(float))
b = np.array([6,3,14,8],dtype = np.dtype(float))

In [9]:
d = np.linalg.det(A)

x = np.linalg.solve(A,b)

print(f"Determinant of matrix A: {d:.2f}")

print(f"Solution vector: {x}")

Determinant of matrix A: -17.00
Solution vector: [2. 3. 4. 1.]


In [11]:
def MultiplyRow(M, row_num, row_num_multiple):
    # .copy() function is required here to keep the original matrix without any changes
    M_new = M.copy()     
    
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new
    
def AddRows(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()     
    
    M_new[row_num_2] = M_new[row_num_1] * row_num_1_multiple + M_new[row_num_2]
    return M_new

def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()     
    
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

In [12]:
A_test = np.array([
        [1,-2,3,4],
        [-5,6,-7,8],
        [-4,3,-2,1],
        [8,-7,6,-5]    
    ],dtype=np.dtype(float))
print("Original matrix:")
print(A_test)

print("\nOriginal matrix after its third row is multiplied by -2:")
print(MultiplyRow(A_test,2,-2))

print("\nOriginal matrix after exchange of the third row with the sum of itself and first row multiplied by 4:")
print(AddRows(A_test,0,2,4))

print("\nOriginal matrix after exchange of its first and third rows:")
print(SwapRows(A_test,0,2))


Original matrix:
[[ 1. -2.  3.  4.]
 [-5.  6. -7.  8.]
 [-4.  3. -2.  1.]
 [ 8. -7.  6. -5.]]

Original matrix after its third row is multiplied by -2:
[[ 1. -2.  3.  4.]
 [-5.  6. -7.  8.]
 [ 8. -6.  4. -2.]
 [ 8. -7.  6. -5.]]

Original matrix after exchange of the third row with the sum of itself and first row multiplied by 4:
[[ 1. -2.  3.  4.]
 [-5.  6. -7.  8.]
 [ 0. -5. 10. 17.]
 [ 8. -7.  6. -5.]]

Original matrix after exchange of its first and third rows:
[[-4.  3. -2.  1.]
 [-5.  6. -7.  8.]
 [ 1. -2.  3.  4.]
 [ 8. -7.  6. -5.]]
